# Generated by Django 5.2.3 on 2025-07-30 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Original filename as uploaded', max_length=255)),
                ('file_path', models.CharField(help_text='Relative path to the file from MEDIA_ROOT', max_length=500)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('gif', 'GIF'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], help_text='Category of file type', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(help_text='Secure access token for file retrieval', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration time for file access', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether file can be accessed without authentication')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'files_file',
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Original filename as uploaded', max_length=255)),
                ('file_path', models.CharField(help_text='Relative path to the file from MEDIA_ROOT', max_length=500)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('gif', 'GIF'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], help_text='Category of file type', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(help_text='Secure access token for file retrieval', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration time for file access', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether file can be accessed without authentication')),
            ],
            options={
                'verbose_name': 'Profile Image',
                'verbose_name_plural': 'Profile Images',
                'db_table': 'files_profile_image',
            },
        ),
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Original filename as uploaded', max_length=255)),
                ('file_path', models.CharField(help_text='Relative path to the file from MEDIA_ROOT', max_length=500)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('gif', 'GIF'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], help_text='Category of file type', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(help_text='Secure access token for file retrieval', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration time for file access', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether file can be accessed without authentication')),
                ('message_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the message this file belongs to', null=True)),
                ('message_content_type', models.ForeignKey(blank=True, help_text='Type of message this file belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Chat File',
                'verbose_name_plural': 'Chat Files',
                'db_table': 'files_chat_file',
            },
        ),
    ]
