# Generated by Django 5.2.3 on 2025-07-30 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directmessagemessage',
            name='direct_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.directmessage'),
        ),
        migrations.AddField(
            model_name='directmessagemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['last_interaction'], name='chat_direct_last_in_9219e0_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['user1', 'user2'], name='chat_direct_user1_i_d9110d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='directmessage',
            unique_together={('user1', 'user2')},
        ),
    ]
